package Clinic.med.API.domain.medicals;


public enum Specialty {
    ORTOPEDIA,
    CARDIOLOGIA,
    GINECOLOGIA,
    DERMATOLOGIA,
    NEUROLOGIA,
    PEDIATRIA,
    GASTROENTEROLOGIA,
    ENDOCRINOLOGIA,
    OFTALMOLOGIA,
    REUMATOLOGIA,
    PSIQUIATRIA,
    CIRURGIA_GERAL,


}
